---
- name: provisining for anyway environment
  hosts: all
  become: true

  vars_files:
    - vars/main.yml
    - vars/secret.yml.vault

  roles:
    - role: galaxy/kamaln7.swapfile
    - role: galaxy/geerlingguy.nginx
    - role: galaxy/geerlingguy.java
    - role: galaxy/geerlingguy.mysql
